"""run_pafi.py — generated by the pafi-setup skill.

Inputs the skill consumed from this folder:
  - calc.py        -> imports `make_calculator`
  - neb.traj       -> loaded with ase.io.read(..., index=":")
  - submit.slurm   -> filled in as submit_pafi.sh

Grid: r = linspace(0, 1, 11), T = 300 K, smoke-test sizes (nsteps=100).
"""

import os
import numpy as np
from ase.io import read
from mpi4py import MPI
from pafi import PAFIMPI

from calc import make_calculator

# --- NEB images -------------------------------------------------------------
images = read("neb.traj", index=":")

# --- Calculator (worker_comm MUST match the comm passed to the calculator) -
worker_comm = MPI.COMM_SELF
inter_comm = MPI.COMM_WORLD
calc = make_calculator(comm=worker_comm)

# --- PAFI -------------------------------------------------------------------
pafi = PAFIMPI(images, calc, worker_comm=worker_comm, inter_comm=inter_comm)

json_file = "pafi_results.json"
if os.path.exists(json_file):
    pafi.read_json(json_file)

rank = MPI.COMM_WORLD.Get_rank()
if rank == 0:
    pafi.plot_neb("neb_energy.png")

temperatures = [300.0]
r_values = np.linspace(0.0, 1.0, 11)

for T in temperatures:
    for r in r_values:
        pafi.run(
            r,
            T=T,
            nsteps=100,
            thermsteps=100,
            minsteps=5,
            verbose=(rank == 0),
        )
        if rank == 0:
            r_arr = np.array(pafi.data["r"])
            T_arr = np.array(pafi.data["target_T"])
            dF_arr = np.array(pafi.data["dF"])
            mask = np.isclose(r_arr, r) * np.isclose(T_arr, T)
            print(
                f"  r={r:.2f}  T={T:.0f}K  "
                f"n_samples={mask.sum()}  <dF>={dF_arr[mask].mean():.4f} eV"
            )
            pafi.write_json(json_file)
